### ISSUE TITLE
How can I create key?

### ISSUE THREAD

**Issue by scorpioRED** [volodymyrlut/passbook.js#4]
Доброго дня. Хочу заюзати Ваш модуль. У Вас досить зрозуміла інструкція, проте або я все ж таки не в'їзджаю, або apple внесла зміни. Я завантажив свій Pass Type ID сертифікат, потім із в'язки експортував його у форматі .pem. Але я не можу зрозуміти де взяти чи згенерити ключ pkey.pem чи pkey.p12 ? П.С.   .p12 формату у мене взагалі нічого немає

**Comment by volodymyrlut** [comment]
@scorpioRED Привіт, Віталій.

У вас MacOS? Спробуйте експортувати свої ключі у форматі p12 з keychain'у. https://stackoverflow.com/a/14954163 - тут є відповідь про те, чому у вас може не бути такої можливості.

**Comment by scorpioRED** [comment]
Так, у мене macOS, дякую за лінк.
Зараз ваш модуль генерить мені `pass.pkpass` без жодних помилок, проте цей файл ні IOS ні macOS не відкриває  

> The pass “pass.pkpass” could not be opened.

у колбеку також ніякої інфи
`passbook_js.createPassbook('coupon', 'Coupon.raw/', 'keys/', 'password',function (err, ress) {
    console.log('err ->> ', err );  // err ->>  undefined
    console.log('res ->> ', ress ); // res ->>  undefined
});`
У консолі наче все ок 

> pass.json file redaded successfully

**Comment by volodymyrlut** [comment]
@scorpioRED Ну .pkpass - це завжди архів, ви можете його відкрити і подивитися, що всередині.
Причин того, що він не відкривається, може бути безліч. Спробуйте вікрити його через якийсь додаток зплеймаркету на Android - зазвичай вони хапають всі файли. Тоді з імовірністю 100% проблема зі збіркою ключів.

**Comment by scorpioRED** [comment]
Наразі заюзав просто `passbook` без вашої обгортки, все ок файл відкривається нормально, я так думаю, що причина в тому, що модуль `passbook` вже давно не обновлявся і можливо не підтримує якихось опцій із нового `pass.json`, а так як Ваш модуль повністю кидає всі атрибути з `pass.json` в `passbook`, то в результаті й получається збій. Дякую, за Ваш витрачений час

**Comment by volodymyrlut** [comment]
@scorpioRED Віталій, радий, що у вас все вийшло.
Справа в тім, що я створив це репо ще коли був дуже зеленим джуном і я боюся його зараз відкривати навіть. Можливо я колись знайду час на його апдейт.

Дякую за ваш час теж. Якщо захочете щось імпрувнути - надішліть PR (якщо зрозумієте, в чому там проблема). Я б був дуже вдячним.
